### ISSUE TITLE
help fast :(

### ISSUE THREAD

**Issue by rolkoztm** [DaanGamesDG/PaperPlane#87]
yo started paper plane and cant get into websit
![Nu7xzyWg](https://user-images.githubusercontent.com/60612933/151940613-446cb051-b6d7-40a8-8194-171442483840.png)
![DgyRyhvU](https://user-images.githubusercontent.com/60612933/151940633-eb1432d1-3e7e-4a71-b09e-194796550f3e.png)

**Comment by DaanGamesDG** [comment]
You configured your DNS settings incorrectly

**Comment by rolkoztm** [comment]
ok fixed, when loggin in i have this problem :
![l8868BFG](https://user-images.githubusercontent.com/60612933/151943129-276a4454-4d46-4a5e-984c-9760b49f4836.png)

**Comment by DaanGamesDG** [comment]
Go to https://paperplane.daangamesdg.xyz/docs/get-started#installation -> check the **

**Comment by rolkoztm** [comment]
yes but it have 32 characters

**Comment by DaanGamesDG** [comment]
Not according to the error, do you use pm2

**Comment by rolkoztm** [comment]
oh
no i dont

**Comment by DaanGamesDG** [comment]
Doesn’t matter

**Comment by DaanGamesDG** [comment]
If you did, env might not have been updated

**Comment by DaanGamesDG** [comment]
But try restarting the app

**Comment by rolkoztm** [comment]
tried

**Comment by DaanGamesDG** [comment]
Show me the key pls

**Comment by rolkoztm** [comment]
![6IfgNRaA](https://user-images.githubusercontent.com/60612933/151944593-2c37454c-78dc-4cd4-8412-504aa72a56b7.png)

**Comment by DaanGamesDG** [comment]
Generate a new one with numbers and letters only

**Comment by rolkoztm** [comment]
ty for help

**Comment by DaanGamesDG** [comment]
Np :)
