### ISSUE TITLE
Moving to another server

### ISSUE THREAD

**Issue by Mazeee1** [DaanGamesDG/PaperPlane#97]
Hi.
How can I move PaperPlane to another server? I’m moving to another host, and I want to keep all my previous photos. 

Thanks :)

**Comment by DaanGamesDG** [comment]
Copy and paste everything except the `node_modules` folder from the old server to the new one, after that follow the installation guide

**Comment by Mazeee1** [comment]
Hi.

Cloudflare is showing this when I go to my cdn.
![image](https://user-images.githubusercontent.com/79224065/160887130-ae95a4f7-e57e-4551-870b-6fe714142fa1.png)

But when I go to the IP directly (myip:3000), it shows this error when I try to sign in.
![image](https://user-images.githubusercontent.com/79224065/160887320-3638bba8-265b-4096-bf93-038288b3f222.png)

**Comment by Mazeee1** [comment]
Never mind, I figured it out. Thanks anyway :)

**Comment by DaanGamesDG** [comment]
apologies, did not see your comment until now. Tho looks like you already fixed it, idk how you did that but my brother which uses this CDN too has the same problem and I can't fix it lmao. What did you do to fix it?
